sudo: required
language: node_js
node_js:
  - "stable"
services:
  - docker

cache:
  directories:
  - node_modules

install:
  - npm install

before_script:
  - echo "Branch... $TRAVIS_BRANCH"

script:
  - npm test

deploy:
  provider: heroku
  api_key: "0421987e-5a13-47f5-bf64-575a8cdc2065"
  app: felixtestapp2019
